#! /bin/sh
set -eu

if command -v uv >/dev/null; then
    exec uv run --script -- "$@"
fi

if command -v pipx >/dev/null; then
    exec pipx run --path -- "$@"
fi

if command -v hatch >/dev/null; then
    exec hatch run -- "$@"
fi

if command -v pip-run >/dev/null; then
    exec pip-run -- "$@"
fi

echo 'python-script-runner: No compatible Python script runner found.' >&2
echo 'Please install one of: uv, pipx, Hatch, pip-run.' >&2
exit 127
